//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calgroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserRole
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public string AppUser_Id { get; set; }
        public string IdentityRole_Id { get; set; }
    
        public virtual AppRole AppRole { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
