//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calgroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryView
    {
        public string Name { get; set; }
        public string Image { get; set; }
        public string PDF { get; set; }
        public bool Status { get; set; }
        public string AliasCat { get; set; }
        public string Category { get; set; }
    }
}
