//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calgroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linhvuc
    {
        public int LinhvucID { get; set; }
        public string Linhvuc1 { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
