//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calgroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string Alias { get; set; }
        public string Name { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string ImageLink { get; set; }
        public string ImageLinkDetail { get; set; }
        public string ManualLink { get; set; }
        public string Detail { get; set; }
        public string Specification { get; set; }
        public string Price { get; set; }
        public Nullable<int> Hot { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
