//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calgroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Role { get; set; }
        public string Skype { get; set; }
        public string Zalo { get; set; }
        public string Phone { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
